version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
    - echo building the SpringAws
    - git branch -r
    - java -version
    - mvn install
artifacts:
  files:
  - target/*.jar
  discard-paths: yes
cache:
  paths:
  - '/root/.m2/**/*'
