version: 0.2

phases:
  install:
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
  build:
    commands:
    - echo building the SpringAws
    - mvn install
artifacts:
  files:
  - target/*.jar
  discard-paths: yes
cache:
  paths:
  - '/root/.m2/**/*'